apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp101
  namespace: dev
spec:
  replicas: 15
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp101
  template:
    metadata:
      labels:      
        app: webapp101
      annotations:
        kubernetes.io/change-cause: "This is the version 4 of the application"
    spec:
      containers:
      - name: webapp101
        image: jassyboy/roadmapdevops:V4
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: webapp101
  ports:
  - port: 80
    targetPort: 80


