apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp101
  namespace: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: webapp101
  template:
    metadata:
      labels:
        app: webapp101
    spec:
      containers:
      - name: webapp101
        image: jassyboy/roadmapdevops:V1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: webapp101
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30112

