apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hostpath
spec:
  selector:
    matchLabels:
      app: myhost
  template:
    metadata:
      labels:
        app: myhost
    spec:
      volumes:
        - name: var-log-path
          hostPath:
            path: /var/log
      containers:
      - name: myhost-cont
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "sleep"
          - "3600"
        volumeMounts:
          - name:  var-log-path
            mountPath:  /var/log
            readOnly: true
            
