apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
      - name: mongodb-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env: 
        - name: ME_CONFIG_BASICAUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongoexpress-secret
              key: mongoexpress-username

        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongoexpress-secret
              key: mongoexpress-password

        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mymongo-secret
              key: mongodb-username
        
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mymongo-secret
              key: mongodb-password

        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodbexpress-config
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-svc
spec:
  type: NodePort
  selector:
    app: mongodb-express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30011






