apiVersion: apps/v1
kind: Deployment
metadata:
  name: classapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classapp
  template:
    metadata:
      labels:
        app: classapp
    spec:
      containers:
      - name: classapp
        image: slimjaydee/sampleapp:V56
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: classsvc
spec:
  type: NodePort
  selector:
    app: classapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30111
